table fVendas
	lineageTag: d52d6048-7914-49ac-8225-26b17a8a1d0c

	measure 'Receita Líquida' = SUM(fVendas[valor_liquido_brl])
		lineageTag: a1269ad9-7861-4b86-90b6-023db7d53351

	measure 'Receita Bruta' = SUM(fVendas[valor_bruto_brl])
		lineageTag: 10678ed1-989b-4225-bd44-95c9b0a366fe

	measure 'Custo Total' = SUM(fVendas[custo_total_brl])
		lineageTag: 721d5719-2c64-41e7-b741-efc761ab7db0

	measure 'Quantidade Total' = SUM(fVendas[quantidade])
		lineageTag: 4ecbe4e1-6b4f-43a9-9389-1003585d7e9b

	measure 'Preço Médio Unitário' = AVERAGE(fVendas[preco_unitario_brl])
		lineageTag: cb750e4d-a184-46f6-8471-4e97cccb4a49

	measure 'Desconto Médio %' = AVERAGE(fVendas[desconto_pct])
		lineageTag: 3e13009a-49ea-476a-9a4b-5a9d5a47605c

	measure 'Valor Médio Desconto' = AVERAGE(fVendas[valor_desconto_brl])
		lineageTag: 3ac912df-c26e-4c12-a0ee-88b6d008de6d

	measure 'Ticket Médio' = DIVIDE([Receita Líquida], DISTINCTCOUNT(fVendas[id_pedido]), 0)
		lineageTag: f466cf4b-c55e-42b4-876e-ccace40ac39b

	measure 'Clientes Ativos' = DISTINCTCOUNT(fVendas[id_cliente])
		lineageTag: a8b96347-0afa-406d-b00f-61977450df31

	measure 'Vendas Ano Anterior' = CALCULATE([Receita Líquida], SAMEPERIODLASTYEAR(dCalendario[Data]))
		lineageTag: 34dbff71-9f25-476a-9293-f4128bdc4577

	measure 'Vendas 12M' = CALCULATE([Receita Líquida], DATESINPERIOD(dCalendario[Data], MAX(dCalendario[Data]), -12, MONTH))
		lineageTag: 29712eca-0748-4d2a-9f4d-386847a91c41

	measure 'Receita por Unidade' = DIVIDE([Receita Líquida], [Quantidade Total], 0)
		lineageTag: 9f2ab5c9-9974-4a05-a19a-bb58fc073dca

	measure '% Pedidos com Desconto' = DIVIDE(CALCULATE(DISTINCTCOUNT(fVendas[id_pedido]), fVendas[desconto_pct] > 0), DISTINCTCOUNT(fVendas[id_pedido]), 0)
		lineageTag: 45bd996f-bb47-41ea-95d2-aefbcb15f692

	measure 'Contador Anomalias' = COUNTROWS(fVendas_Anomalias)
		lineageTag: 34d026a0-1aa9-41e4-97d6-aad9b68c059e

	measure 'Lucro Bruto' = [Receita Líquida] - [Custo Total]
		lineageTag: d11c97ef-5eed-4b30-81ea-13f501d71eda

	measure 'Margem Bruta %' = DIVIDE([Lucro Bruto], [Receita Líquida], 0)
		lineageTag: dc5144c0-ac31-453a-96b7-9a97db03bbcd

	measure 'Taxa de Repetição' = VAR Clientes = SUMMARIZE(fVendas, fVendas[id_cliente], "Pedidos", DISTINCTCOUNT(fVendas[id_pedido])) VAR ClientesRepetidos = COUNTROWS(FILTER(Clientes, [Pedidos] > 1)) RETURN DIVIDE(ClientesRepetidos, COUNTROWS(Clientes), 0)
		lineageTag: f5a5a578-2db8-44b2-9e87-d6ba085a1190

	measure 'Crescimento YoY %' = DIVIDE([Receita Líquida] - [Vendas Ano Anterior], [Vendas Ano Anterior], 0)
		lineageTag: e8aee18f-346e-41d1-9f1f-f23e70bb22f3

	measure Corr_Qtd_Preco = VAR T = FILTER(ALL(fVendas), NOT(ISBLANK(fVendas[quantidade])) && NOT(ISBLANK(fVendas[preco_unitario_brl]))) VAR N = COUNTROWS(T) VAR MeanQ = AVERAGEX(T, fVendas[quantidade]) VAR MeanP = AVERAGEX(T, fVendas[preco_unitario_brl]) VAR Cov = SUMX(T, (fVendas[quantidade] - MeanQ) * (fVendas[preco_unitario_brl] - MeanP)) / N VAR StdevQ = SQRT(SUMX(T, POWER(fVendas[quantidade] - MeanQ, 2)) / N) VAR StdevP = SQRT(SUMX(T, POWER(fVendas[preco_unitario_brl] - MeanP, 2)) / N) RETURN DIVIDE(Cov, StdevQ * StdevP, BLANK())
		lineageTag: 8f91ca80-beb8-47bc-8041-f8892c127d42

	column id_venda
		dataType: int64
		formatString: 0
		lineageTag: 21dda3b5-b5b4-41b8-a1a0-73994f77a21c
		summarizeBy: sum
		sourceColumn: id_venda

		annotation SummarizationSetBy = Automatic

	column id_pedido
		dataType: int64
		formatString: 0
		lineageTag: 734fd8f0-76f4-46df-ada7-4c246f418b2e
		summarizeBy: sum
		sourceColumn: id_pedido

		annotation SummarizationSetBy = Automatic

	column data_venda
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8831ebef-d38a-4a47-aca8-5fa2c972e929
		summarizeBy: none
		sourceColumn: data_venda

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column id_cliente
		dataType: int64
		formatString: 0
		lineageTag: 478d90b5-2b12-4730-bed0-a66a8b30e6e7
		summarizeBy: none
		sourceColumn: id_cliente

		annotation SummarizationSetBy = Automatic

	column id_produto
		dataType: int64
		formatString: 0
		lineageTag: bc96a565-6bad-46fe-91d7-92d2358448fd
		summarizeBy: none
		sourceColumn: id_produto

		annotation SummarizationSetBy = Automatic

	column quantidade
		dataType: int64
		formatString: 0
		lineageTag: 25b6d25a-b135-4ae8-9377-389a54a80037
		summarizeBy: sum
		sourceColumn: quantidade

		annotation SummarizationSetBy = Automatic

	column preco_tabela_brl
		dataType: double
		lineageTag: f1dd479a-da3f-4a0c-9361-6d4254c78d52
		summarizeBy: sum
		sourceColumn: preco_tabela_brl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column desconto_pct
		dataType: double
		lineageTag: 256153d6-f3ac-430e-9540-0786ac8c826c
		summarizeBy: sum
		sourceColumn: desconto_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column preco_unitario_brl
		dataType: double
		lineageTag: 20c7f283-62df-4078-b9d1-95d74d5487c2
		summarizeBy: sum
		sourceColumn: preco_unitario_brl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column valor_bruto_brl
		dataType: double
		lineageTag: 501692dc-42a5-4b04-9b74-328b494fb2aa
		summarizeBy: sum
		sourceColumn: valor_bruto_brl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column valor_desconto_brl
		dataType: double
		lineageTag: 1a698fa2-0b6d-4cd4-a529-94399da93dbd
		summarizeBy: sum
		sourceColumn: valor_desconto_brl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column valor_liquido_brl
		dataType: double
		lineageTag: ab88b13f-d91a-414c-a28a-6192c7ef167f
		summarizeBy: sum
		sourceColumn: valor_liquido_brl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column custo_total_brl
		dataType: double
		lineageTag: 3cbd1b4f-2dd2-4ab5-ad7e-123bd3c6a16c
		summarizeBy: sum
		sourceColumn: custo_total_brl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column canal_venda
		dataType: string
		lineageTag: 4f001015-0e8d-4639-a766-7a27bcdf07d4
		summarizeBy: none
		sourceColumn: canal_venda

		annotation SummarizationSetBy = Automatic

	column forma_pagamento
		dataType: string
		lineageTag: 8395950b-eca6-4f58-b007-1d5fa11d8299
		summarizeBy: none
		sourceColumn: forma_pagamento

		annotation SummarizationSetBy = Automatic

	partition fVendas = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\roger\Desktop\materiais\raw\fato_vendas_raw.csv"),[Delimiter=";", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"id_venda", Int64.Type}, {"id_pedido", Int64.Type}, {"data_venda", type date}, {"id_cliente", Int64.Type}, {"id_produto", Int64.Type}, {"quantidade", Int64.Type}, {"preco_tabela_brl", type number}, {"desconto_pct", type number}, {"preco_unitario_brl", type number}, {"valor_bruto_brl", type number}, {"valor_desconto_brl", type number}, {"valor_liquido_brl", type number}, {"custo_total_brl", type number}, {"canal_venda", type text}, {"forma_pagamento", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

